name: meu_site
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.8.1
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  web:
    generate: true
    image_path: "assets/eu.jpeg"
    background_color: "#000000"
    theme_color: "000000"

flutter:
  uses-material-design: true

  assets:
    - assets/eu.jpeg
    - assets/educhat.gif
    - assets/simplepdf.gif
    
  
  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Regular.ttf
        - asset: fonts/Nunito-ExtraLight.ttf
          weight: 300


